apiVersion: v1
kind: Service
metadata:
    name: db
    labels:
        name: mysqlservice
        app: go-API
spec:
    ports:
        - port: 3036
          targetPort: 3036
    selector:
        name: mysql-pod
        app: go-API             